require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - "bin/*"
    - "node_modules/**/*"
    - "vendor/**/*"
    - "db/schema.rb"
    - "lib/tasks/*"
  DisplayCopNames: true
  SuggestExtensions: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SymbolProc:
  Enabled: false

Layout/DotPosition:
  Enabled: true
  EnforcedStyle: leading

Metrics/LineLength:
  Max: 240

Metrics/MethodLength:
  Max: 1000

Style/FloatDivision:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Rails/UnknownEnv:
  Environments:
    - development
    - test
    - testing
    - staging
    - production

RSpec/MultipleExpectations:
  Max: 3

RSpec/NestedGroups:
  Max: 5
